#!/bin/sh

rel_dir=$1
if [ -e ${rel_dir}/config/config.yml ]
then
cd ${rel_dir}
rev=`svn log . --limit 1 |
     egrep '^r'  |
     egrep '([0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9])' |
     awk '{print $1}'|awk -F'r' '{print $2}'`

sed -i "" "s/_REVISION_/${rev}/g" ${rel_dir}/config/config.yml
fi
