class CreateOrganizations < ActiveRecord::Migration
  def self.up
    create_table :organizations do |t|
      t.column :name_el, :string
      t.column :name_en, :string
      t.column :domain, :string
    end
    
    Organization.create :name_el => "Ανωτάτη Σχολή Καλών Τεχνών", :domain => "asfa.gr"
    Organization.create :name_el => "Ανωτέρα Εκκλησιαστική Σχολή Θεσσαλονίκης", :domain => "oipp.gr"
    Organization.create :name_el => "Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης", :domain => "auth.gr"
    Organization.create :name_el => "ΑΣΠΑΙΤΕ", :domain => "selete.gr"
    Organization.create :name_el => "Boυλή των Ελλήνων", :domain => "parliament.gr"
    Organization.create :name_el => "Γενική Γραμματεία Έρευνας και Τεχνολογίας", :domain => "gsrt.gr"
    Organization.create :name_el => "Γενική Γραμματεία Πολιτικής Προστασίας", :domain => "gscp.gr"
    Organization.create :name_el => "Γεωπονικό Πανεπιστήμιο Αθηνών", :domain => "aua.gr"
    Organization.create :name_el => "Γεωργική και Βιοτεχνική Σχολή Θεσσαλονίκης", :domain => "afs.edu.gr"
    Organization.create :name_el => "Δημοκρίτειο Πανεπιστήμιο Θράκης", :domain => "duth.gr"
    Organization.create :name_el => "Διαχείριση ΕΔΕΤ", :domain => "grnet.gr"
    Organization.create :name_el => "Διεθνές κέντρο Δημόσιας Διοίκησης", :domain => "untcentre.org"
    Organization.create :name_el => "Δίκτυο Σύζευξις", :domain => "syzefxis.gov.gr"
    Organization.create :name_el => "ΕΚΕΒΕ Α. Φλέμιγκ", :domain => "fleming.gr"
    Organization.create :name_el => "Ε.ΚΕ.ΦΕ Δημόκριτος", :domain => "demokritos.gr"
    Organization.create :name_el => "Εθνικό Αστεροσκοπείο Αθηνών", :domain => "noa.gr"
    Organization.create :name_el => "Εθνικό και Καποδιστριακό Πανεπιστήμιο Αθηνών", :domain => "uoa.gr"
    Organization.create :name_el => "Εθνικό Κέντρο Δημόσιας Διοίκησης", :domain => "ekdd.gr"
    Organization.create :name_el => "Εθνικό Κέντρο Διαβήτη", :domain => "hndc.gr"
    Organization.create :name_el => "Εθνικό Κέντρο Θαλάσσιας Ερευνας", :domain => "ncmr.gr"
    Organization.create :name_el => "Εθνικό Κέντρο Τεκμηρίωσης / EIE", :domain => "ekt.gr"
    Organization.create :name_el => "Εθνικό Μετσόβιο Πολυτεχνείο", :domain => "ntua.gr"
    Organization.create :name_el => "ΕΙΧΗΜΥΘ", :domain => "iceht.gr"
    Organization.create :name_el => "EKETA/Ινστιτούτο Αγροβιοτεχνολογίας", :domain => "certh.gr"
    Organization.create :name_el => "Ελληνικό Ανοιχτό Πανεπιστήμιο", :domain => "eap.gr"
    Organization.create :name_el => "Ελληνικός Οργανισμός Τυποποίησης", :domain => "elot.gr"
    Organization.create :name_el => "Ευρωπαϊκό Κέντρο για την Ανάπτυξη της Επαγγελματικής Κατάρτισης", :domain => "cedefop.gr"
    Organization.create :name_el => "Ερευνητικό Ακαδημαϊκό Ινστιτούτου Τεχνολογίας Υπολογιστών", :domain => "cti.gr"
    Organization.create :name_el => "ΙΑΣΑ", :domain => "iasa.gr"
    Organization.create :name_el => "Ίδρυμα Ευγενίδου", :domain => "eugenfound.edu.gr"
    Organization.create :name_el => "Ίδρυμα Ιατροβιολογικής Έρευνας Ακαδημίας Αθηνών", :domain => "bioacademy.gr"
    Organization.create :name_el => "Ιδρυμα Τεχνολογίας  Ερευνας", :domain => "forth.gr"
    Organization.create :name_el => "Ινστ. Pasteur", :domain => "pasteur.gr"
    Organization.create :name_el => "Ινστ. Γεωλογικών & Μεταλλευτικών Ερευνών", :domain => "igme.gr"
    Organization.create :name_el => "Ινστ. Επεξεργασίας Λόγου", :domain => "ilsp.gr"
    Organization.create :name_el => "Ινστιτούτο Θαλάσσιας Βιολογίας", :domain => "imbc.gr"
    Organization.create :name_el => "Ινστιτούτο Πολιτιστικής & Εκπαιδευτικής Τεχνολογίας", :domain => "ceti.gr"
    Organization.create :name_el => "Ινστιτούτο Τεχνικής Σεισμολογίας & Αντισεισμικών Κατασκευών", :domain => "itsak.gr"
    Organization.create :name_el => "Ιόνιο Πανεπιστήμιο", :domain => "ioniο.gr"
    Organization.create :name_el => "Κέντρο Ανανεώσιμων Πηγών Ενέργειας", :domain => "cres.gr"
    Organization.create :name_el => "Κέντρο Ερευνας για Θέματα Ισότητας", :domain => "kethi.gr"
    Organization.create :name_el => "Κέντρο Ελληνικής Γλώσσας", :domain => "komvos.edu.gr"
    Organization.create :name_el => "Κέντρο Ερευνών ΝΕΣΤΩΡ", :domain => "nestor.org.gr"
    Organization.create :name_el => "Οικονομικό Πανεπιστήμιο Αθηνών", :domain => "aueb.gr"
    Organization.create :name_el => "Οργανισμός Αντισεισμικής Προστασίας", :domain => "oasp.gr"
    Organization.create :name_el => "ΟΤΕ – Συγκρότημα Εργαστηρίων Νέων Τεχνολογιών & Υπηρεσιών", :domain => "oteresearch.gr"
    Organization.create :name_el => "Πανελλήνιο Σχολικό Δίκτυο – EDUnet", :domain => "sch.gr"
    Organization.create :name_el => "Πανεπιστήμιο Αιγαίου", :domain => "aegean.gr"
    Organization.create :name_el => "Πανεπιστήμιο Θεσσαλίας", :domain => "uth.gr"
    Organization.create :name_el => "Πανεπιστήμιο Ιωαννίνων", :domain => "uoi.gr"
    Organization.create :name_el => "Πανεπιστήμιο Κρήτης", :domain => "uoc.gr"
    Organization.create :name_el => "Πανεπιστήμιο Μακεδονίας", :domain => "uom.gr"
    Organization.create :name_el => "Πανεπιστήμιο Πατρών", :domain => "upatras.gr"
    Organization.create :name_el => "Πανεπιστήμιο Πειραιά", :domain => "unipi.gr"
    Organization.create :name_el => "Πανεπιστήμιο Πελλοπονήσου", :domain => "uop.gr"
    Organization.create :name_el => "Πάντειον Πανεπιστήμιο", :domain => "panteion.gr"
    Organization.create :name_el => "Πολυτεχνείο Κρήτης", :domain => "tuc.gr"
    Organization.create :name_el => "Πυροσβεστική Ακαδημία", :domain => "fire-dept-academy.gr"
    Organization.create :name_el => "Ρυθμιστική Αρχή Ενέργειας", :domain => "rae.gr"
    Organization.create :name_el => "Σχολή Ικάρων", :domain => "hafa.gr"
    Organization.create :name_el => "Στρατιωτική Σχολή Ευελπίδων", :domain => "sse.gr"
    Organization.create :name_el => "Σχολή Ναυτικών Δοκίμων", :domain => "hna.gr"
    Organization.create :name_el => "ΤΕΙ Αθηνών", :domain => "teiath.gr"
    Organization.create :name_el => "ΤΕΙ Δυτικής Μακεδονίας", :domain => "teikoz.gr"
    Organization.create :name_el => "ΤΕΙ Ηπείρου", :domain => "teiep.gr"
    Organization.create :name_el => "ΤΕΙ Ιονίου", :domain => "teiion.gr"
    Organization.create :name_el => "ΤΕΙ Θεσσαλονίκης", :domain => "teithe.gr"
    Organization.create :name_el => "ΤΕΙ Καβάλας", :domain => "teikav.edu.gr"
    Organization.create :name_el => "ΤΕΙ Καλαμάτας", :domain => "teikal.gr"
    Organization.create :name_el => "ΤΕΙ Κρήτης", :domain => "teiher.gr"
    Organization.create :name_el => "ΤΕΙ Λαμίας", :domain => "teilam.gr"
    Organization.create :name_el => "ΤΕΙ Λάρισας", :domain => "teilar.edu.gr"
    Organization.create :name_el => "ΤΕΙ Μεσσολογίου", :domain => "teimess.gr"
    Organization.create :name_el => "ΤΕΙ Πάτρας", :domain => "teipat.gr"
    Organization.create :name_el => "ΤΕΙ Πειραιά", :domain => "teipir.gr"
    Organization.create :name_el => "ΤΕΙ Σερρών", :domain => "teiser.gr"
    Organization.create :name_el => "ΤΕΙ Χαλκίδας", :domain => "teihal.gr"
    Organization.create :name_el => "Υπουργείο Εθνικής Οικονομίας", :domain => "ypetho.gr"
    Organization.create :name_el => "Υπουργείο Εθνικής Παιδείας & Θρησκευμάτων", :domain => "ypepth.gr"
    Organization.create :name_el => "Χαροκόπειο Πανεπιστήμιο", :domain => "hua.gr"
    Organization.create :name_el => "Athens Information Technology", :domain => "ait.edu.gr"
  end

  def self.down
    drop_table :organizations
  end
end
